apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260623-224618-mtfwl35lq2m7-service
spec:
  selector:
    app: enterprise-system-20260623-224618-mtfwl35lq2m7
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
